# Generated by Django 5.1.2 on 2024-10-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0002_remove_anonmessage_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonmessage',
            name='key',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
