# Generated by Django 5.1.2 on 2024-10-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textApp', '0003_anonmessage_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonmessage',
            name='key',
        ),
    ]
